- Dockerfile
Fixed issue with version on deployments
Build the docker image
> Backport: "Dockerfile with version to fix deployment"

- docker-compose.yml
Docker compose added
Deploy the docker compose
> docker compose added

- docker-compose.yml
Added email config on docker compose
Run docker compose
> Added email config

- docker-compose.yml
Added db config
Run docker compose
> Added db config

- frontend/src/metabase/env.js
- frontend/src/metabase/query_builder/components/WebSocketHandler.jsx
- src/metabase/server/middleware/security.clj
> wss url working

- frontend/src/metabase/query_builder/components/WebSocketHandler.jsx
Add Insights handler on WebSocketHandler
> GetInsights WebSocketHandler

- webpack.config.js
> fixed semantic url

- frontend/src/metabase/api/cubeApi.ts
- frontend/src/metabase/browse/components/BrowseCubes.tsx
- frontend/src/metabase/browse/components/CubeHeader.tsx
- frontend/src/metabase/components/Cube/CubePreviewTable.tsx
- frontend/src/metabase/components/ItemsTable/BaseItemsTable.styled.tsx
- frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/MainNavbarView.tsx
- src/metabase/server/middleware/security.clj
- webpack.config.js
This is the inital table design for preview section.
> inital table for preview section

- frontend/src/metabase/api/database.ts
- frontend/src/metabase/browse/components/BrowseCubes.tsx
- frontend/src/metabase/components/Cube/CubePreviewTable.tsx
> implemented metabase native table

- frontend/src/metabase/components/FeedbackDialog/FeedbackDialog.jsx
- frontend/src/metabase/query_builder/components/WebSocketHandler.jsx
Updated feedback to popup in a new tab and also populate the email with the chat history
> detailed feedback

- frontend/src/metabase/query_builder/components/WebSocketHandler.jsx
Removed unused hook that thrown an error on the chat
> removed hook

- frontend/src/metabase/components/Cube/utils.tsx
- webpack.config.js
> changed company name and fixed wrapper bug

- resources/migrations/001_update_migrations.yaml
Fixed the statement of create function so it doesn't break if the function already exists
> fixed migrations function declaration

- resources/migrations/001_update_migrations.yaml
Fixed author and TS on migrations
> fixed author and ts on migrations

- frontend/src/metabase/browse/components/BrowseChat.tsx
- frontend/src/metabase/browse/components/BrowseInsights.tsx
- frontend/src/metabase/browse/components/ChatItems/InitialOptions.tsx
- frontend/src/metabase/browse/components/ChatItems/Prompt.tsx
- frontend/src/metabase/browse/components/ChatItems/Welcome.tsx
- frontend/src/metabase/components/ChatMessageList/ChatMessageList.js
- frontend/src/metabase/components/ChatMessageList/Message.js
- frontend/src/metabase/home/components/HomeXrayCard/HomeXrayCard.styled.tsx
- frontend/src/metabase/home/components/HomeXrayCard/HomeXrayCard.tsx
- frontend/src/metabase/query_builder/components/WebSocketHandler.jsx
Fixed chat functionalities, designs, new implementations
> minor fixes

- frontend/src/metabase/api/dataset.ts
- frontend/src/metabase/browse/components/BrowseCubes.tsx
- frontend/src/metabase/components/Cube/CubeFlow.tsx
- frontend/src/metabase/components/Cube/CubePreviewTable.tsx
- frontend/src/metabase/components/Cube/utils.tsx
Fixed cubeFlow bug and optimized the preview table
> table optimized and cubeflowbug fixed

- frontend/src/metabase/browse/components/BrowseCubes.tsx
- frontend/src/metabase/components/Cube/utils.tsx
fixed line break issue while saving cube
> fixed line break issue

- frontend/src/metabase/App.styled.tsx
- frontend/src/metabase/browse/components/BrowseContainer.styled.tsx
- frontend/src/metabase/browse/components/ChatItems/ChatHistory.tsx
- frontend/src/metabase/components/ChatMessageList/Message.js
- frontend/src/metabase/components/FeedbackDialog/FeedbackDialog.jsx
- frontend/src/metabase/query_builder/components/WebSocketHandler.jsx
Fixed overlap on chat, added new ongoing components and updated some styles
> feedback card and fixes

- frontend/src/metabase/components/ChatMessageList/Message.js
- frontend/src/metabase/components/FeedbackDialog/FeedbackDialog.jsx
Completed feedback card design
> feedback card completed

- frontend/src/metabase/browse/components/BrowseChat.tsx
- frontend/src/metabase/browse/components/BrowseInsights.tsx
- frontend/src/metabase/browse/components/ChatItems/ChatHistory.tsx
Seperated Chat history getInsights and dataAgents
> seperated two chat history

- frontend/src/metabase-types/api/database.ts
- frontend/src/metabase/api/database.ts
- frontend/src/metabase/nav/components/AppBar/AppBarLarge.tsx
fixed breadcrumb bug and also created a endpoint
> fixed breadcrumb bug and also created a endpoint

- resources/migrations/001_update_migrations.yaml
Fixed migrations file versions
> fixed migrations file

- frontend/src/metabase-types/store/initialMessage.ts
- frontend/src/metabase-types/store/state.ts
- frontend/src/metabase/browse/components/BrowseChat.tsx
- frontend/src/metabase/browse/components/BrowseInsights.tsx
- frontend/src/metabase/browse/components/ChatItems/Prompt.tsx
- frontend/src/metabase/browse/components/ChatItems/Welcome.tsx
- frontend/src/metabase/home/components/HomeLayout/HomeLayout.tsx
- frontend/src/metabase/home/components/InsightsLayout/InsightsLayout.styled.tsx
- frontend/src/metabase/home/components/InsightsLayout/InsightsLayout.tsx
- frontend/src/metabase/home/components/InsightsLayout/InsightsLayout.unit.spec.tsx
- frontend/src/metabase/home/components/InsightsLayout/index.ts
- frontend/src/metabase/query_builder/components/ChatAssistant.jsx
- frontend/src/metabase/redux/initialMessage.ts
- frontend/src/metabase/routes.jsx
- frontend/src/metabase/store.js
> insights working

- frontend/src/metabase/query_builder/components/ChatAssistant.jsx
> fixed used db id

- frontend/src/metabase/query_builder/components/ChatAssistant.jsx
> resolved url

- src/metabase/driver/common.clj
Project name changes on DB Connections
> db name change

- frontend/src/metabase/browse/components/DatabasesConnections.tsx
- frontend/src/metabase/styled-components/containers/GlobalStyles/GlobalStyles.tsx
Redirect after successful connection
Inter font added
> db connection redirect

- frontend/src/metabase/home/components/HomeLayout/HomeLayout.tsx
- frontend/src/metabase/nav/components/ProfileLink/ProfileLink.jsx
- frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/MainNavbarView.tsx
> new ui settings

- frontend/src/metabase/query_builder/components/ChatAssistant.jsx
even if one of the card of insights fails the rest of the cards should work
> added some error handling for getInsights

- frontend/src/metabase/components/ChatMessageList/ChatMessageList.js
- frontend/src/metabase/query_builder/components/ChatAssistant.jsx
added extra functionality for handling the new getInsights
> rendering new getInsights Images

- frontend/src/metabase/admin/databases/components/DatabaseList/DatabaseList.jsx
- frontend/src/metabase/admin/databases/containers/DatabaseEditApp.tsx
- frontend/src/metabase/lib/urls/admin.ts
Fixed admin routes for admin panel
> fixed admin routes

- frontend/src/metabase/browse/components/BrowseDatabases.tsx
- frontend/src/metabase/browse/components/BrowseDatabasesSchemas.tsx
- frontend/src/metabase/browse/components/SchemasTable.tsx
- frontend/src/metabase/browse/components/TableBrowser/TableBrowser.jsx
- frontend/src/metabase/routes.jsx
Added schema component to allow schema filtering when fetching tables from database
> fixed schema tables render

- frontend/src/metabase/browse/components/BrowseDatabasesSchemas.tsx
- frontend/src/metabase/browse/components/TableBrowser/TableBrowser.styled.tsx
- frontend/src/metabase/nav/components/AppBar/AppBarLarge.tsx
- frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionDataSource/QuestionDataSource.jsx
Added DB breadcrumbs with updated cards for the tables
> db breadcrumbs

- frontend/src/metabase/browse/components/BrowseValidation.tsx
- frontend/src/metabase/components/PaginationControls/PaginationControls.tsx
- frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/MainNavbarView.tsx
- frontend/src/metabase/routes.jsx
- frontend/src/metabase/visualizations/components/TableSimple/TableSimple.styled.tsx
Validation page first approach
> validation first approach

- frontend/src/metabase/components/ChatMessageList/ChatMessageList.js
- frontend/src/metabase/components/Insight/InsightCode.jsx
- frontend/src/metabase/components/Insight/InsightImg.jsx
- frontend/src/metabase/components/Insight/InsightPlan.jsx
- frontend/src/metabase/components/Insight/InsightText.jsx
- frontend/src/metabase/query_builder/components/ChatAssistant.jsx
- resources/migrations/001_update_migrations.yaml
- src/metabase/public_settings.clj
fixed two bugs... and also implemented new version of getInsights
> new flow of get insights

- frontend/src/metabase/browse/components/BrowseValidation.tsx
Fixed rerender on validation page
> fixed validation rerender

- frontend/src/metabase/browse/components/BrowseValidation.tsx
- frontend/src/metabase/components/PaginationControlsCustom/PaginationControlsCustom.tsx
- frontend/src/metabase/components/PaginationControlsCustom/PaginationControlsCustom.unit.spec.tsx
- frontend/src/metabase/components/PaginationControlsCustom/index.tsx
> pagination fix

- frontend/src/metabase/databases/components/DatabaseEngineField/DatabaseEngineField.tsx
added redshift option into database connection
> added redshift option to databases connection

- frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/MainNavbarView.tsx
Removed Validation link until V2 is done
> remove validation link until done

- frontend/src/metabase/browse/components/BrowseChat.tsx
- frontend/src/metabase/browse/components/BrowseInsights.tsx
- frontend/src/metabase/home/components/HomeLayout/HomeLayout.tsx
- frontend/src/metabase/query_builder/components/ChatAssistant.jsx
Chat history new button to move into a new chat
> updated chat history interactions

- frontend/src/metabase/browse/components/BrowseChat.tsx
- frontend/src/metabase/home/components/HomeLayout/HomeLayout.tsx
- frontend/src/metabase/query_builder/components/ChatAssistant.jsx
fixed messages remaining active while switching from insights to normal chat
> fixed messages remaining active while switching chats

- frontend/src/metabase/query_builder/components/expressions/ExpressionEditorHelpText/ExpressionEditorHelpText.tsx
Remove DocumentationLink and LearnMoreIcon from the Custom Expression pop-up helper
> Remove Lear More link button on Custom Expressions

- frontend/src/metabase/query_builder/components/LimitInput.tsx
Fix Limit rows cannot be negative
> Fix Limit rows cannot be negative

- frontend/src/metabase/browse/components/BrowseCubes.tsx
- frontend/src/metabase/browse/components/CubeTable.tsx
> bugfix data

- frontend/src/metabase/browse/components/CubeTable.tsx
fixed data fetch, including cubes with comments or multiple lines on the SQL code
> fixed data fetching

- frontend/src/metabase/browse/components/BrowseCubes.tsx
- frontend/src/metabase/browse/components/CubeTable.tsx
- frontend/src/metabase/components/Cube/utils.tsx
> fixed cubes format

- frontend/src/metabase/components/ChatMessageList/Message.js
- frontend/src/metabase/query_builder/components/ChatAssistant.jsx
Semantic Layer error from assistant
> Semantic Layer error from assistant

- deps.edn
- frontend/src/metabase/browse/components/CompanySettings/Databases.tsx
- frontend/src/metabase/databases/components/DatabaseEngineField/DatabaseEngineField.tsx
> Oracle JDBC Driver

- frontend/src/metabase/components/CubeRequest/CubeRequestDialog.jsx
added missing fields for the post
> added missing fields

- src/metabase/api/cubes_requests.clj
- src/metabase/models/cubes_requests.clj
Added new column definitions to clojure files
> cubes_requests added new columns to clojure definitions

- frontend/src/metabase/browse/components/CompanySettings/CompanyImage.tsx
Add loader on CompanyImage component
> Add loader on CompanyImage component

- frontend/src/metabase-types/store/Suggestions.ts
- frontend/src/metabase-types/store/state.ts
- frontend/src/metabase/auth/actions.ts
- frontend/src/metabase/browse/components/ChatItems/InitialOptions.tsx
- frontend/src/metabase/home/components/HomeCard/HomeCard.tsx
- frontend/src/metabase/home/components/HomeLayout/HomeLayout.tsx
- frontend/src/metabase/home/components/HomeXrayCard/HomeXrayCard.styled.tsx
- frontend/src/metabase/home/components/HomeXrayCard/HomeXrayCard.tsx
- frontend/src/metabase/redux/suggestionsSlice.ts
- frontend/src/metabase/store.js
- locales/es.po
Suggestions on GetData and Insights
> Suggestions

- frontend/src/metabase/home/components/HomeLayout/HomeLayout.tsx
- frontend/src/metabase/routes.jsx
> Grettings on chat

- frontend/src/metabase/query_builder/components/ChatAssistant.jsx
Show message when isPossible is maybe after the result
> Show message when isPossible is maybe after the result

- frontend/src/metabase/components/ErrorPages/ErrorPages.tsx
- frontend/src/metabase/home/components/HomeLayout/HomeLayout.tsx
Add Screen error message if no DB or SL
> Add Screen error message if no DB or SL

- frontend/src/metabase/home/components/HomeLayout/HomeLayout.tsx
> Fix Routes between chats

- frontend/src/metabase/query_builder/components/ChatAssistant.jsx
- src/metabase/server/middleware/security.clj
added omniloy to security allowance
> chat-v3 ensure security allowance

- frontend/src/metabase/query_builder/components/ChatAssistant.jsx
> chat-v3 fixed issues

- frontend/src/metabase/home/components/HomeLayout/HomeLayout.tsx
- frontend/src/metabase/query_builder/components/ChatAssistant.jsx
ensure correct chat type is used for each case 
also removed old ws connections for now
> chat-v3 fixed chat type issue

- frontend/src/metabase/browse/components/BrowseContainer.styled.tsx
- frontend/src/metabase/home/components/HomeLayout/HomeLayout.tsx
- frontend/src/metabase/query_builder/components/ChatAssistant.jsx
Updated how data is fetched and rendered to match the new responses from the assistant
> chat-v3 fix no messages displayed

- frontend/src/metabase/components/ChatMessageList/ChatMessageList.js
- frontend/src/metabase/components/ChatMessageList/Message.js
- frontend/src/metabase/query_builder/components/ChatAssistant.jsx
fixed correct rendering order of the messages
> chat-v3 correct order displayed

- frontend/src/metabase/nav/containers/MainNavbar/SidebarItems/SidebarItems.styled.tsx
Updated sidebar color to fix hover clarity
> sidebar element colors

- frontend/src/metabase/browse/components/BrowseSemanticHeader.tsx
- frontend/src/metabase/browse/components/BrowseSemanticLayers.tsx
- frontend/src/metabase/components/Cube/CubeConnection.tsx
Removed cube configuration options since we are gonna migrate to automatic creation of the semantic layer
> semantic layer removed cube configuration

- frontend/src/metabase/browse/components/ChatItems/ChatHistory.tsx
- frontend/src/metabase/home/components/HomeLayout/HomeLayout.tsx
- frontend/src/metabase/query_builder/components/ChatAssistant.jsx
> chat v3 bugs fixed

- frontend/src/metabase/components/ChatMessageList/ChatMessageList.js
- frontend/src/metabase/query_builder/components/ChatAssistant.jsx
ensuring multiple cards are rendered correctly
> multiple cards rendered

- frontend/src/metabase/query_builder/components/ChatAssistant.jsx
Added error messages to be displayed when occured
> display error messages

- frontend/src/metabase/query_builder/components/ChatAssistant.jsx
> display error messages on event

- frontend/src/metabase/home/components/HomeLayout/HomeLayout.tsx
removed one toast from homelayout since it has no use anymore
> removed ununsed toast

- frontend/src/metabase/query_builder/components/ChatAssistant.jsx
updated run id to match the last chunk
> feedback run id updated

- frontend/src/metabase/components/ChatMessageList/ChatMessageList.js
- frontend/src/metabase/query_builder/components/ChatAssistant.jsx
no cards are removed now when accessing the details
> no card removal

- frontend/src/metabase/components/ChatMessageList/ChatMessageList.js
- frontend/src/metabase/query_builder/components/ChatAssistant.jsx
> redirect on verify click fix

- frontend/src/metabase/auth/actions.ts
- frontend/src/metabase/home/components/HomeLayout/HomeLayout.tsx
- frontend/src/metabase/query_builder/components/ChatAssistant.jsx
> session token

- frontend/src/metabase/browse/components/ChatItems/ChatHistory.tsx
Now chathistory reveals only those items related to the selected company
> history based on company

- frontend/src/metabase/query_builder/components/ChatAssistant.jsx
native query added to hash generator
> native query

- frontend/src/metabase/query_builder/components/ChatAssistant.jsx
> assistant by id

- frontend/src/metabase/query_builder/components/ChatAssistant.jsx
allowing multiple content format to be used avoiding errors
> multiple content format allowed

- frontend/src/metabase/home/components/HomeLayout/HomeLayout.tsx
- frontend/src/metabase/query_builder/components/ChatAssistant.jsx
nwe thread now works correctly
> new thread creation

- frontend/src/metabase/query_builder/components/ChatAssistant.jsx
fixed duplicated messages and first messages dissapearing
> fixed duplicated messages

- frontend/src/metabase/query_builder/components/ChatAssistant.jsx
> comment cards

- frontend/src/metabase/components/ChatMessageList/ChatMessageList.js
- frontend/src/metabase/query_builder/components/ChatAssistant.jsx
removed logs, removed empty line
> removed logs

- frontend/src/metabase/browse/components/ChatItems/ChatHistory.tsx
- frontend/src/metabase/home/components/HomeLayout/HomeLayout.tsx
- frontend/src/metabase/query_builder/components/ChatAssistant.jsx
- locales/es.po
- locales/metabase.pot
> translations

- frontend/src/metabase/components/ChatMessageList/ChatMessageList.js
- frontend/src/metabase/components/ChatMessageList/Message.js
- locales/es.po
- locales/metabase.pot
> markdown getdata

- frontend/src/metabase/components/Insight/InsightPlan.jsx
- locales/es.po
- locales/metabase.pot
remaining strings to be translated, fixed
> remaining trads

- frontend/src/metabase/components/ChatMessageList/ChatMessageList.js
- frontend/src/metabase/components/ChatMessageList/Message.js
fixed markdown margins and icons rendering
> markdown and icons

- frontend/src/metabase/home/components/HomeLayout/HomeLayout.tsx
- frontend/src/metabase/query_builder/components/ChatAssistant.jsx
- frontend/src/metabase/ui/components/icons/Icon/icons/index.ts
- frontend/src/metabase/ui/components/icons/Icon/icons/stop.svg
minor fixes and improvements on the chat
> chat fixes

- frontend/src/metabase/query_builder/components/ChatAssistant.jsx
removed chat loader when getting to the end of the fetching data, so we don't have to wait for the finally to finish
> forced chat loader to false

- frontend/src/metabase/home/components/HomeLayout/HomeLayout.tsx
- frontend/src/metabase/query_builder/components/ChatAssistant.jsx
> custom db input modal
